name: release

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            bin_path: ./target/release/RustyBear-Engine
          - platform: macos-latest
            bin_path: ./target/release/RustyBear-Engine
          - platform: windows-latest
            bin_path: ./target/release/RustyBear-Engine.exe
        
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
    - name: Install libudev
      run: sudo apt install -y libudev-dev
      if: runner.os == 'Linux' 
    - name: Build engine
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.platform }}
        path: ${{ matrix.bin_path }}
        
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Pull tags
      run: git fetch --prune --unshallow --tags
      
    - name: Check if tag to be created does not yet exist
      run: |
        TAG=v$(awk '$1 == "version" {print $3}' Cargo.toml  | head  | tr -d "\"" | head -n1)
        if git rev-parse $TAG >/dev/null 2>&1; then
          echo "Tag $TAG already exists"
          exit 1
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV
      continue-on-error: true
    
    - name: Download Windows executable
      uses: actions/download-artifact@v2
      with:
        name: windows-latest
        path: RustyBear-Engine.exe
      if: env.TAG

    - name: Download Linux executable
      uses: actions/download-artifact@v2
      with:
        name: ubuntu-latest
        path: RustyBear-Engine-linux
      if: env.TAG
      
    - name: Download macOS executable
      uses: actions/download-artifact@v2
      with:
        name: macos-latest
        path: RustyBear-Engine-macOS
      if: env.TAG
    
    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          RustyBear-Engine.exe
          RustyBear-Engine-linux
          RustyBear-Engine-macOS
        tag_name: v${{ env.TAG }}
        draft: true
        fail_on_unmatched_files: true
        generate_release_notes: true
      if: env.TAG
      
